namespace WowCombatStats.Models.Enums;

public enum ItemType
{
    Head = 0,
    Neck = 1,
    Shoulder = 2,
    Back = 3,
    Shirt = 4,
    Tabard = 5,
    Wrist = 6,
    Hands = 7,
    Waist = 8,
    Legs = 9,
    Feet = 10,
    Ring = 11,
    Trinket = 12,
    Sword = 13,
    Dager = 14,
    Mace = 15,
    Axe = 16,
    TwoHandSword = 17,
    TwoHandMace = 18,
    TwoHandAxe = 19,
    FistWeapons = 20,
    Stave = 21,
    Polearm = 22,
    FishingPole = 23,
    Bow = 24,
    Gun = 25,
    Crossbow = 26,
    Thrown = 27,
    Wand = 28,
    Mount = 29,
}