namespace WowCombatStats.Models.Enums;

public enum ItemTypeInfo
{
    Unknown = 1,
    Head = 2,
    Neck = 3,
    Shoulder = 4,
    Back = 5,
    Shirt = 6,
    Tabard = 7,
    Wrist = 8,
    Hands = 9,
    Waist = 10,
    Legs = 11,
    Feet = 12,
    Ring = 13,
    Trinket = 14,
    Sword = 15,
    Dager = 16,
    Mace = 17,
    Axe = 18,
    TwoHandSword = 19,
    TwoHandMace = 20,
    TwoHandAxe = 21,
    FistWeapons = 22,
    Stave = 23,
    Polearm = 24,
    FishingPole = 25,
    Bow = 26,
    Gun = 27,
    Crossbow = 28,
    Thrown = 29,
    Wand = 30,
    Mount = 31,
}