// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WowCombatStats.Data;

#nullable disable

namespace WowCombatStats.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220117201101_changeAddUserToken")]
    partial class changeAddUserToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Boss", b =>
                {
                    b.Property<int>("BossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BossId"));

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("RaidTypeId")
                        .HasColumnType("integer");

                    b.HasKey("BossId");

                    b.HasIndex("RaidTypeId");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.ClassType", b =>
                {
                    b.Property<int>("ClassTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassTypeId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassTypeId");

                    b.ToTable("ClassTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.FactionType", b =>
                {
                    b.Property<int>("FactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactionTypeId"));

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FactionTypeId");

                    b.ToTable("FactionTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsParse")
                        .HasColumnType("boolean");

                    b.Property<int?>("RaidId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FileId");

                    b.HasIndex("RaidId");

                    b.HasIndex("UserId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Gear", b =>
                {
                    b.Property<int>("GearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GearId"));

                    b.Property<int>("BackId")
                        .HasColumnType("integer");

                    b.Property<int>("FeetId")
                        .HasColumnType("integer");

                    b.Property<int>("FirstRingId")
                        .HasColumnType("integer");

                    b.Property<int>("FirstTrinketId")
                        .HasColumnType("integer");

                    b.Property<int>("HandsId")
                        .HasColumnType("integer");

                    b.Property<int>("HeadId")
                        .HasColumnType("integer");

                    b.Property<int>("LegsId")
                        .HasColumnType("integer");

                    b.Property<int>("MainHandId")
                        .HasColumnType("integer");

                    b.Property<int>("NeckId")
                        .HasColumnType("integer");

                    b.Property<int>("OffHandId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RangeId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondRingId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondTrinketId")
                        .HasColumnType("integer");

                    b.Property<int>("ShirtId")
                        .HasColumnType("integer");

                    b.Property<int>("ShoulderId")
                        .HasColumnType("integer");

                    b.Property<int>("TabardId")
                        .HasColumnType("integer");

                    b.Property<int>("WaistId")
                        .HasColumnType("integer");

                    b.Property<int>("WristId")
                        .HasColumnType("integer");

                    b.HasKey("GearId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Gears");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.GenderType", b =>
                {
                    b.Property<int>("GenderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenderTypeId"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenderTypeId");

                    b.ToTable("GenderTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Guild", b =>
                {
                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuildId"));

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RarityTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("RarityTypeId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTypeId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("ClassTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.Property<int>("GenderTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<string>("GuildRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastGearId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerLvl")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("ClassTypeId");

                    b.HasIndex("FactionId");

                    b.HasIndex("GenderTypeId");

                    b.HasIndex("GuildId");

                    b.HasIndex("PlayerName")
                        .IsUnique();

                    b.HasIndex("RaceTypeId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.PlayerAttr", b =>
                {
                    b.Property<int>("PlayerAttrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerAttrId"));

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<int>("ArcaneResistance")
                        .HasColumnType("integer");

                    b.Property<int>("Armor")
                        .HasColumnType("integer");

                    b.Property<int>("FireResistance")
                        .HasColumnType("integer");

                    b.Property<int>("FrostResistance")
                        .HasColumnType("integer");

                    b.Property<int>("Healt")
                        .HasColumnType("integer");

                    b.Property<int>("Intellect")
                        .HasColumnType("integer");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.Property<int>("MeleeCrit")
                        .HasColumnType("integer");

                    b.Property<int>("MeleeHit")
                        .HasColumnType("integer");

                    b.Property<int>("NatureResistance")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ShadowResistance")
                        .HasColumnType("integer");

                    b.Property<int>("SpellCrit")
                        .HasColumnType("integer");

                    b.Property<int>("SpellHit")
                        .HasColumnType("integer");

                    b.Property<int>("Spirit")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("PlayerAttrId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerAttrs");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.PlayerStat", b =>
                {
                    b.Property<int>("PlayerStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerStatId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerStatTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("RaidId")
                        .HasColumnType("integer");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerStatId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerStatTypeId");

                    b.HasIndex("RaidId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.PlayerStatType", b =>
                {
                    b.Property<int>("PlayerStatTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerStatTypeId"));

                    b.Property<string>("PlayerStatName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerStatTypeId");

                    b.ToTable("PlayerStatType");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RaceType", b =>
                {
                    b.Property<int>("RaceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceTypeId"));

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RaceTypeId");

                    b.ToTable("RaceTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Raid", b =>
                {
                    b.Property<int>("RaidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaidId"));

                    b.Property<DateTime>("EndRaid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RaidTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartRaid")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaidId");

                    b.HasIndex("RaidTypeId");

                    b.HasIndex("ServerId");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RaidComposition", b =>
                {
                    b.Property<int>("RaidCompositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaidCompositionId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RaidId")
                        .HasColumnType("integer");

                    b.HasKey("RaidCompositionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaidId");

                    b.ToTable("RaidCompositions");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RaidLoot", b =>
                {
                    b.Property<int>("RaidLootId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaidLootId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RaidId")
                        .HasColumnType("integer");

                    b.HasKey("RaidLootId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaidId");

                    b.ToTable("RaidLoots");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RaidType", b =>
                {
                    b.Property<int>("RaidTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaidTypeId"));

                    b.Property<string>("RaidName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RaidTypeId");

                    b.ToTable("RaidTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RarityType", b =>
                {
                    b.Property<int>("RarityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RarityTypeId"));

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RarityTypeId");

                    b.ToTable("RarityTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerId"));

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ServerId");

                    b.HasIndex("VersionTypeId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Token")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.VersionType", b =>
                {
                    b.Property<int>("VersionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VersionTypeId"));

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VersionTypeId");

                    b.ToTable("VersionTypes");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Boss", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.RaidType", null)
                        .WithMany()
                        .HasForeignKey("RaidTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.File", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.Raid", null)
                        .WithMany()
                        .HasForeignKey("RaidId");

                    b.HasOne("WowCombatStats.Models.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Gear", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Item", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.ItemType", null)
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.RarityType", null)
                        .WithMany()
                        .HasForeignKey("RarityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Player", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.ClassType", null)
                        .WithMany()
                        .HasForeignKey("ClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.FactionType", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.GenderType", null)
                        .WithMany()
                        .HasForeignKey("GenderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.RaceType", null)
                        .WithMany()
                        .HasForeignKey("RaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.PlayerAttr", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.Player", "Player")
                        .WithOne("PlayerAttr")
                        .HasForeignKey("WowCombatStats.Models.DataModels.PlayerAttr", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.PlayerStat", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.PlayerStatType", null)
                        .WithMany()
                        .HasForeignKey("PlayerStatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.Raid", null)
                        .WithMany()
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Raid", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.RaidType", null)
                        .WithMany()
                        .HasForeignKey("RaidTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RaidComposition", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.Raid", null)
                        .WithMany()
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.RaidLoot", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowCombatStats.Models.DataModels.Raid", null)
                        .WithMany()
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Server", b =>
                {
                    b.HasOne("WowCombatStats.Models.DataModels.VersionType", null)
                        .WithMany()
                        .HasForeignKey("VersionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WowCombatStats.Models.DataModels.Player", b =>
                {
                    b.Navigation("PlayerAttr")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
